Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: ServerlessReleaseDashboardWAF
      Scope: CLOUDFRONT
      Description: WAF to prevent all access except for admin IP
      DefaultAction:
        Block: {}
      Rules:
        - Name: IPSetWAFRule
          Priority: 0
          Action:
            Allow: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFIPSet.Arn
          VisibilityConfig:
            SampledRequestsEnabled: false
            CloudWatchMetricsEnabled: false
            MetricName: IPSetWAFRule
      VisibilityConfig:
        SampledRequestsEnabled: false
        CloudWatchMetricsEnabled: false
        MetricName: DefaultAction

  WAFIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: ServerlessReleaseDashboardAdminIP
      Scope: CLOUDFRONT
      Addresses:
        - ${self:custom.ADMIN_IP_ADDRESS}
      Description: Only allow access from my IP
      IPAddressVersion: IPV4
