service: release-dashboard

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  logRetentionInDays: 7
  tags:
    App: ${self:service}
    ManagedBy: serverless framework

  apiGateway:
    shouldStartNameWithService: true

  httpApi:
    cors:
      allowedOrigins:
        - https://release.fw
        - http://localhost:8080
      allowedHeaders:
        - Content-Type
        - Authorization
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - "${opt:region, self:provider.region}"
              - ".amazonaws.com/"
              - Ref: CognitoUserPool
        audience:
          - Ref: CognitoUserPoolClient

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:DescribeUserPoolClient
        - cognito-idp:InitiateAuth
        - cognito-idp:ListUsers
      Resource:
        - !GetAtt CognitoUserPool.Arn
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt DynamoDBTable.Arn
        - !Join
          - ""
          - - !GetAtt DynamoDBTable.Arn
            - /index/repo

custom: ${file(.env.${self:provider.stage}.yaml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  - ${file(serverless/functions/create_repo.yaml)}
  - ${file(serverless/functions/create_user.yaml)}
  - ${file(serverless/functions/delete_repo.yaml)}
  - ${file(serverless/functions/delete_user.yaml)}
  - ${file(serverless/functions/list_repos.yaml)}
  - ${file(serverless/functions/list_users.yaml)}
  - ${file(serverless/functions/login_user.yaml)}
  - ${file(serverless/functions/release.yaml)}
  - ${file(serverless/functions/reset_user_password.yaml)}

resources:
  - ${file(serverless/cloudformation/cognito.yaml)}
  - ${file(serverless/cloudformation/dynamodb.yaml)}
  # - ${file(serverless/cloudformation/s3.yaml)}
