service: release-dashboard

frameworkVersion: "2"

custom: ${file(.env.${self:provider.stage}.yaml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**
  individually: true

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 128
  logRetentionInDays: 7
  tags:
    App: ${self:service}
    Environment: ${self:provider.stage}
    ManagedBy: serverless framework

  apiGateway:
    shouldStartNameWithService: true

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:8080
        - https://${self:custom.DOMAIN}
        - !Sub https://${CloudfrontDistribution.DomainName}
      allowedHeaders:
        - Content-Type
        - Authorization
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
        audience:
          - Ref: CognitoUserPoolClient

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:DescribeUserPoolClient
        - cognito-idp:InitiateAuth
        - cognito-idp:ListUsers
      Resource:
        - !GetAtt CognitoUserPool.Arn
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt DynamoDBTable.Arn
        - !Sub ${DynamoDBTable.Arn}/index/repo

functions:
  - ${file(deployments/functions/create_repo.yaml)}
  - ${file(deployments/functions/create_user.yaml)}
  - ${file(deployments/functions/delete_repo.yaml)}
  - ${file(deployments/functions/delete_user.yaml)}
  - ${file(deployments/functions/list_repos.yaml)}
  - ${file(deployments/functions/list_users.yaml)}
  - ${file(deployments/functions/login_user.yaml)}
  - ${file(deployments/functions/release.yaml)}
  - ${file(deployments/functions/reset_user_password.yaml)}
  - ${file(deployments/functions/verify_auth.yaml)}

resources:
  - ${file(deployments/cloudformation/acm.yaml)}
  - ${file(deployments/cloudformation/cloudfront.yaml)}
  - ${file(deployments/cloudformation/cognito.yaml)}
  - ${file(deployments/cloudformation/dynamodb.yaml)}
  - ${file(deployments/cloudformation/s3.yaml)}
  - ${file(deployments/cloudformation/waf.yaml)}
