service: release-dashboard

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  logRetentionInDays: 7
  tags:
    App: ${self:service}
    ManagedBy: serverless framework

  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminInitiateAuth
      Resource:
        - !GetAtt [CognitoUserPool, Arn]

custom: ${file(.env.${self:provider.stage}.yaml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  - ${file(serverless/functions/create_user.yaml)}
  - ${file(serverless/functions/delete_user.yaml)}
  - ${file(serverless/functions/login_user.yaml)}
  - ${file(serverless/functions/release.yaml)}

resources:
  - ${file(serverless/cognito.yaml)}
