service: release-dashboard

frameworkVersion: "2"

custom: ${file(.env.${self:provider.stage}.yaml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**
  individually: true

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 128
  logRetentionInDays: 7
  versionFunctions: false
  tags:
    App: ${self:service}
    Environment: ${self:provider.stage}
    ManagedBy: serverless framework

  apiGateway:
    shouldStartNameWithService: true

  httpApi:
    payload: "2.0"
    cors:
      allowedOrigins:
        - http://localhost:8080
        # - https://${self:custom.DOMAIN}
        # - !Sub https://${CloudfrontDistribution.DomainName}
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Session-Id
      allowCredentials: true
      maxAge: 600

    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
        audience:
          - Ref: CognitoUserPoolClient

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:DescribeUserPoolClient
        - cognito-idp:InitiateAuth
        - cognito-idp:ListUsers
      Resource:
        - !GetAtt CognitoUserPool.Arn
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt DynamoDBTable.Arn
        - !Sub ${DynamoDBTable.Arn}/index/repo

functions:
  - ${file(deployments/functions/releases_create.yaml)}
  - ${file(deployments/functions/repositories_create.yaml)}
  - ${file(deployments/functions/repositories_delete.yaml)}
  - ${file(deployments/functions/repositories_list.yaml)}
  - ${file(deployments/functions/users_create.yaml)}
  - ${file(deployments/functions/users_delete.yaml)}
  - ${file(deployments/functions/users_list.yaml)}
  - ${file(deployments/functions/users_login.yaml)}
  - ${file(deployments/functions/users_reset_password.yaml)}

  - ${file(deployments/custom_resources/custom_resources.yaml)}

resources:
  # - ${file(deployments/cloudformation/acm.yaml)}
  # - ${file(deployments/cloudformation/cloudfront.yaml)}
  - ${file(deployments/cloudformation/custom_resources.yaml)}
  - ${file(deployments/cloudformation/cognito.yaml)}
  - ${file(deployments/cloudformation/dynamodb.yaml)}
  # - ${file(deployments/cloudformation/s3.yaml)}
  # - ${file(deployments/cloudformation/waf.yaml)}
